singleQuote: true
semi: false
plugins:
  - prettier-plugin-astro
  - prettier-plugin-tailwindcss
pluginSearchDirs: false
tailwindFunctions:
  - classNames
  - clsx
overrides:
  - files: '*.astro'
    options:
      parser: astro
