extends:
  - stylelint-config-recommended-scss
  - stylelint-config-html/astro
  - stylelint-config-prettier-scss
plugins:
  - stylelint-scss
rules:
  selector-pseudo-class-no-unknown: [true, { ignorePseudoClasses: [global] }]
  scss/at-rule-no-unknown: null
