# See https://github.com/dawaltconley/cfn-static-website

AWSTemplateFormatVersion: 2010-09-09
Description: Resources for Soraya Palmer's website

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W3002 # ignore warnings about dependency on the `package` command

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: sorayapalmer.com
      SubjectAlternativeNames:
        - '*.sorayapalmer.com'
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: sorayapalmer.com
          ValidationDomain: sorayapalmer.com
  StaticWebsite:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./node_modules/@dawaltconley/cfn-static-website/static-website.template.yaml
      Parameters:
        Domain: sorayapalmer.com
        Subdomain: www
        Redirect: SubdomainToApex
        TrailingSlash: 'false'
        Route53Dns: 'false'
        CertificateArn: !Ref Certificate
        CloudFrontPriceClass: PriceClass_100
        CloudFrontSecurityPolicy: TLSv1.2_2021
        CloudFrontCachePolicy: CachingOptimized
  GitHubDeployment:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./node_modules/@dawaltconley/cfn-static-website/git-pipeline.template.yaml
      Parameters:
        SiteBucket: !GetAtt StaticWebsite.Outputs.SiteBucket
        SourceLocation: https://github.com/dawaltconley/soraya-palmer.git
        SourceBranch: main
        EnvironmentImage: aws/codebuild/standard:7.0
        UseBuildArtifacts: 'false'
        CacheType: S3
        CacheExpiration: 30
        ParameterStoreArns: !Sub "\
          arn:aws:ssm:us-east-1:${AWS::AccountId}:parameter/FontAwesomeProToken,\
          arn:aws:ssm:us-east-1:${AWS::AccountId}:parameter/SorayaPalmer/TinaClientId,\
          arn:aws:ssm:us-east-1:${AWS::AccountId}:parameter/SorayaPalmer/TinaContentToken,\
          arn:aws:ssm:us-east-1:${AWS::AccountId}:parameter/SorayaPalmer/TinaSearchToken"
        AlarmEmail: web@dylan.ac

  # Site Api
  ApiDomain:
    Type: AWS::ApiGateway::DomainName
    DependsOn:
      - ContactFormApi
      - SiteApi
    Properties:
      DomainName: api.sorayapalmer.com
      CertificateArn: !Ref Certificate
      SecurityPolicy: TLS_1_2
  ContactFormApi: # see https://github.com/dawaltconley/contact-api/blob/main/docs/template.md
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./node_modules/@dawaltconley/contact-api/dist/build/template.yaml
      Parameters:
        Email: 'sorayapalmerwrites@gmail.com'
        Required: 'name,email,subject,message'
        Honeypot: 'fax_number'
        AllowOrigin: 'https://sorayapalmer.com'
  ContactFormApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref ApiDomain
      BasePath: contact-form
      RestApiId: !GetAtt ContactFormApi.Outputs.ApiId
      Stage: !GetAtt ContactFormApi.Outputs.ApiStageName
  SiteApi:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./aws/api.template.yaml
      Parameters:
        AllowOrigin: 'https://sorayapalmer.com'
        MailerliteApiKey: /SorayaPalmer/MailerliteApiKey
        MailerliteHoneypot: 'fax_number'
  SiteApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref ApiDomain
      RestApiId: !GetAtt SiteApi.Outputs.ApiId
      Stage: !GetAtt SiteApi.Outputs.ApiStageName

Outputs:
  SiteDomain:
    Value: !GetAtt StaticWebsite.Outputs.FullDomain
  SiteDistributionDomain:
    Value: !GetAtt StaticWebsite.Outputs.DistributionDomainName
  SiteBucket:
    Value: !GetAtt StaticWebsite.Outputs.SiteBucket
  ApiDomain:
    Value: !GetAtt ApiDomain.DistributionDomainName
  ApiDomainAlias:
    Value: !Ref ApiDomain
