version: 0.2

env:
  variables:
    NODE_ENV: production
  parameter-store:
    FA_PRO_TOKEN: FontAwesomeProToken
    TINA_CLIENT_ID: /SorayaPalmer/TinaClientId
    TINA_CONTENT_TOKEN: /SorayaPalmer/TinaContentToken
    TINA_SEARCH_TOKEN: /SorayaPalmer/TinaSearchToken

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Updating npm and node_modules"
      - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
      - npm config set "//npm.fontawesome.com/:_authToken" $FA_PRO_TOKEN
      - npm install --cache .npm
  build:
    on-failure: ABORT
    commands:
      - npm run build
  post_build:
    commands:
      - |
        aws s3 sync --delete dist s3://$SITE_BUCKET \
          --cache-control 'max-age=31536000' \
          --exclude="*" \
          --include="_astro/*" \
          --include="_responsive-images/*" \
          --include="media/trailer/*" \
          --include="fonts/*" \
          --size-only
      - |
        aws s3 sync --delete dist s3://$SITE_BUCKET \
          --cache-control 'no-cache' \
          --exclude="_astro/*" \
          --exclude="_responsive-images/*" \
          --exclude="media/trailer/*" \
          --exclude="fonts/*"

cache:
  paths:
    - 'node_modules/**/*'
    - '.npm/**/*'
    - '.cache/**/*'
    - 'dist/_responsive-images/*'
    - 'dist/media/**/*'
