query writingSamples {
  home(relativePath: "home.mdx") {
    writing {
      title
      selections {
        item {
          ... on Writing {
            url
            title
            image
            imageControls {
              alt
              size
              posX
              posY
            }
            publisher
            description
          }
        }
      }
      linkText
    }
  }
}
