query writingSamples {
  home(relativePath: "home.yaml") {
    writing {
      title
      selections {
        item {
          ... on Writing {
            url
            title
            image
            publisher
            description
          }
        }
      }
    }
  }
}
